jworpdress-web/src/main/java/cn/liuhaihua/web/vo/PostVO.java
/**
 * MIT License
 * Copyright (c) 2018 haihua.liu
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package cn.liuhaihua.web.vo;

import java.util.List;

import cn.liuhaihua.web.model.WpPosts;
import cn.liuhaihua.web.util.HtmlFilterUtil;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * @ClassName: PostVO
 * @Description: 文章展示VO类
 * @author Liuhaihua
 * @date 2018年8月22日
 *
 */
@Data
@EqualsAndHashCode(callSuper=false)
public class PostVO  extends WpPosts {
	/**
	 * 标签和分类
	 */
	private  List<TermsVO>  termsList;
	/**
	 * 文章摘要
	 */
	public String getPostExcerpt(){
		String delHTMLTagstr =HtmlFilterUtil.delHTMLTag(getPostContent());
		if(delHTMLTagstr.length()>200){
			return delHTMLTagstr.substring(0, 200)+"...";
		}else{
			return delHTMLTagstr+"...";
		}
	}
}

jworpdress-web/src/main/resources/templates/index.ftl
<#include "include/macros.ftl">
<@header title="${config.siteName?if_exists} | 追心中的海，逐世界的梦"
    keywords="${config.homeKeywords?if_exists}"
    description="${config.homeDesc?if_exists}"
    canonical="/${config.siteUrl?if_exists}">
</@header>

<div class="container custome-container">
    <!--[if lt IE 9]><div class="alert alert-danger topframe" role="alert">Oh My God！你的浏览器实在<strong>太太太太太太旧了</strong>，赶紧升级浏览器 <a target="_blank" class="alert-link" href="http://browsehappy.com">立即升级</a></div><![endif]-->
    <#if config.maintenance?if_exists && config.maintenance>
    <div class="alert alert-warning fade-in" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        系统预计将在<strong>${config.maintenanceData?string('yyyy年MM月dd日 HH点mm分')}</strong>进行更新，届时网站将无法使用，更新时间大约 5-10分钟，敬请悉知。
    </div>
    </#if>
    <nav class="breadcrumb">
        <div class="notify"><i class="fa fa-volume-up"></i></div>
        <div id="scrolldiv">
            <div class="scrolltext">
                <ul class="list-unstyled" id="notice-box">
                    <li class="scrolltext-title">
                        <a href="javascript:void(0)" rel="bookmark">本站正式启用新域名:<a href="http:/www.liuhaihua.cn" target="_blank"><strong>http:/www.liuhaihua.cn</strong></a></a>
                    </li>
                    <li class="scrolltext-title">
                        <a href="javascript:void(0)" rel="bookmark">活了二十多年，没能为祖国、为人民做点什么，每思及此，伤心欲绝。</a>
                    </li>
                    <li class="scrolltext-title">
                        <a href="javascript:void(0)" rel="bookmark">其实我们可以将所有的问题归结为两种：一种是没饭吃饿出来的；一种是吃饱了撑出来的。</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="row">
        <div class="col-sm-8 blog-main">
            <#if page.list?exists && (page.list?size > 0)>
                <#list page.list as item>
                    <article class="fade-in">
                        <figure class="thumbnail">
                            <a href="${config.siteUrl}/posts/${item.id?c}">
                                <#if item.coverImage?exists && (item.coverImage?length > 7)>
                                    <img width="150" height="150" data-original="${config.qiuniuBasePath}${item.coverImage}-img_150x150" class="img-responsive lazy-img" alt="${item.postTitle?if_exists}">
                                <#else>
                                    <img width="150" height="150" src="${config.siteUrl}/img/default_article_cover.jpg" class="img-responsive lazy-img" alt="${item.postTitle?if_exists}">
                                </#if>
                            </a>
                              <#if item.termsList?exists && (item.termsList?size > 0)>
                             	  <#list item.termsList as term>
                             	      <#if term.taxonomy?exists && (term.taxonomy=='category')>
                          				 		<span class="cat"><a href="${config.siteUrl}/type/${term.termId?if_exists}">${term.name?if_exists}</a></span>
                          			   </#if>
                          		  </#list>
                             </#if>
                        </figure>
                        <header class="entry-header">
                            <h2 class="entry-title">
                                <a href="${config.siteUrl}/archives/${item.id?c}" rel="bookmark" title="点击查看文章详情" data-toggle="tooltip" data-placement="bottom">${item.postTitle}</a>
                            </h2>
                        </header>
                        <div class="entry-content">
                            <div class="archive-content">
                                ${item.postExcerpt?if_exists}
                            </div>
                            <span class="title-l"></span>
                            <span class="entry-meta">
                                <span class="date" title="文章发表日期" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-calendar-o fa-fw"></i>${item.postDate?string('yyyy-MM-dd')}</span>
                                <span class="views" title="文章阅读次数" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-eye fa-fw"></i>浏览(${item.lookCount!(0)})</span>
                                <span class="comment" title="文章评论次数" data-toggle="tooltip" data-placement="bottom">
                                    <a href="${config.siteUrl}/article/${item.id?c}#comment-box" rel="external nofollow">
                                        <i class="fa fa-comments-o fa-fw"></i>评论(${item.commentCount!(0)})
                                    </a>
                                </span>
                            </span>
                            <div class="clear"></div>
                            <span class="entry-more">
                                <a href="${config.siteUrl}/article/${item.id?c}" rel="bookmark" title="点击查看文章详情" data-toggle="tooltip" data-placement="bottom">阅读全文</a>
                            </span>
                        </div>
                    </article>
                </#list>
                <@pageBar></@pageBar>
            <#else >
                <article class="fade-in" style="height: auto">
                    <div class="rows">
                        <div class="col-md-10 col-sm-12">
                            <div class="h3 text-center">亲，啥也没找到啊~~<img src="http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/15/j_thumb.gif" alt="[囧]"></div>
                            <div class="h5 text-center">换个姿势，再来一次~~</div>
                        </div>
                        <div class="col-md-2 col-sm-12">
                            <img src="${config.staticWebSite}/img/wrong.gif" class="center-block" alt="惩罚我" style="width: 110px;margin-top: -10px;">
                        </div>
                    </div>
                    <form action="/" method="post" class="form-horizontal searchForm">
                        <input type="hidden" name="pageNumber" value="1">
                        <div class="input-group">
                            <input type="text" class="form-control br-none" name="keywords" placeholder="换个姿势，再来一次~~">
                            <span class="input-group-btn">
                                <button class="btn btn-default br-none nav-search-btn pointer" type="submit"><i class="fa fa-search"></i> 搜索</button>
                            </span>
                        </div>
                        <div class="clear" style="margin-bottom: 10px"></div>
                        <ul class="list-unstyled list-inline search-hot">
                            <li><strong style="position: relative;top: 2px;color: #999999;">热门搜索：</strong></li>
                            <li><a class="pointer" rel="external nofollow"><span class="label label-default">Java</span></a></li>
                            <li><a class="pointer" rel="external nofollow"><span class="label label-primary">Springboot</span></a></li>
                            <li><a class="pointer" rel="external nofollow"><span class="label label-success">Linux</span></a></li>
                            <li><a class="pointer" rel="external nofollow"><span class="label label-info">Maven</span></a></li>
                            <li><a class="pointer" rel="external nofollow"><span class="label label-warning">Bootstrap</span></a></li>
                            <li><a class="pointer" rel="external nofollow"><span class="label label-danger">阿里云</span></a></li>
                        </ul>
                    </form>
                </article>
            </#if>
        </div>
        <#include "layout/sidebar.ftl"/>
    </div>
</div>
<section class="links index-links">
    <ul class="list-unstyled list-inline">
        <#if indexLinkList?exists && (indexLinkList?size > 0)>
            <#list indexLinkList as item>
                <li>
                    <a href="${item.url}" target="_blank" title="${item.description?if_exists}" data-toggle="tooltip" data-placement="bottom">
                        <img src="${item.favicon}" alt="${item.name?if_exists}" onerror="this.src='${config.staticWebSite}/img/user.png'">${item.name?if_exists}
                    </a>
                </li>
            </#list>
            <li>
                <a href="${config.siteUrl}/links" title="更多链接" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-plus"></i>更多链接</a>
            </li>
        <#else>
            <li>
                <a href="${config.siteUrl}/links" title="申请友链" data-toggle="tooltip" data-placement="bottom">申请友链</a>
            </li>
        </#if>
    </ul>
</section>

<@footer></@footer>